language: python

python:
  - "2.7"
  - "2.6"
  
git:
  depth: 3
  
branches:
  only:
  - v1.0
  - master
  
before_install:
  # install python dev libs
  - sudo apt-get -y install python-dev python-pip python-setuptools
  - sudo pip install --upgrade pip
  - sudo apt-get -y install zlib1g-dev libpng-dev libjpeg-dev 
  - sudo apt-get -y install build-essential libssl-dev libffi-dev
  - sudo apt-get -y install libtesseract-dev libleptonica-dev
  - sudo apt-get -y install cython
  - sudo pip install Cython
  - sudo apt-get -y install tesseract-ocr
  - sudo apt-get -y install tesseract-ocr-fra


before_script:
  # install xml parser for metalex.xmlised module
  - sudo apt-get -y install python-html5lib python-lxml python-bs4


script:
  # run static analysis tools on modified files if needed
  - cd test/
  - python runMetalex.py -h  --stderr
  - python runMetalex.py -p 'projectTestName' -c 'testAuthor' 'testComment' 'testContributors' -d 'dicImages' -r 'file_Rule.dic' -l 'fra' -s  --stderr

