language: python

python:
  - "2.7"

os:
  - linux
  
matrix:
  include:
    - os: linux
      dist: xenial
  fast_finish: true

git:
  depth: 3
  
branches:
  only:
  - v2.0
  - master
  
notifications:
  email:
    recipients:
      - julestawo@yahoo.fr
    on_success: always # default: change
    on_failure: always # default: always
    
before_install:
  # install python dev libs
  - sudo apt-get update
  - sudo apt-get -y install zlib1g-dev libpng-dev libjpeg-dev 
  - sudo apt-get -y install build-essential libssl-dev libffi-dev 
  - sudo apt-get -y install cython
  - sudo apt-get install gcc g++
  - sudo apt-get install autoconf automake libtool checkinstall
  - sudo apt-get -y install python-html5lib python-lxml python-bs4
  - sudo apt-get install tesseract-ocr libtesseract-dev libleptonica-dev
  - sudo apt-get -y install tesseract-ocr-fra
  - CPPFLAGS=-I/usr/local/include pip install tesserocr
  - sudo pip install --upgrade pip  
  - sudo pip install http://effbot.org/downloads/Imaging-1.1.7.tar.gz
  - sudo pip install Cython pillow termcolor
  - sudo pip install utilspie

script:
  # run static analysis tools on modified files if needed (running test)
  - python test/runMetalex.py -h  --stderr
  - python test/runMetalex.py -p 'p_ocropy' -c 'author' 'comment' 'contributors' -d 'imagesInput' -r 'file_Rule.dic' -l 'fra' -o ocropy -m modeldef -s  --stderr
  - python test/runMetalex.py -p 'p_tesserocr' -c 'author' 'comment' 'contributors' -d 'imagesInput' -r 'file_Rule.dic' -l 'fra' -o tesserocr -s  --stderr

